// Auto-generated by scripts/minify.ts
// DO NOT EDIT MANUALLY
// Source: src/scripts/persist.ts

/**
 * Minified version of persist.ts
 * Pre-minified to match browser bundle transformations.
 */
export const MINIFIED_PERSIST = "function persist(t,e,o,n,l,r){let i=null;try{const o=t&&localStorage.getItem(e+\":\"+t);if(o){const t=JSON.parse(o);\"object\"==typeof t&&null!=t&&(i=t)}}catch(t){}if(!i)return;let c=null;if(i&&\"object\"==typeof i){const t=Object.keys(i);if(t.length>0){const e=t[0],o=e?i[e]:null;o&&\"object\"==typeof o&&\"layout\"in o&&(c=o.layout)}}const s=document.querySelector(\"[\"+o+'=\"'+l+'\"]');if(s&&c){const t=s.getAttribute(n||\"\");if(t){const e=parseInt(t,10),o=c.find((function(t){return t.order===e}));o&&s.style.setProperty(r,String(o.size))}}}import{PanelLayoutItem,SerializedPanelGroupState}from\"../utils/serialization\";";
