// Auto-generated by scripts/minify.ts
// DO NOT EDIT MANUALLY
// Source: src/scripts/persist.ts

/**
 * Minified version of persist.ts
 * Pre-minified to match browser bundle transformations.
 */
export const MINIFIED_PERSIST = "function persist(t,e,o,l=3){let c=null;try{const o=t&&localStorage.getItem(e+\":\"+t);if(o){const t=JSON.parse(o);\"object\"==typeof t&&null!=t&&(c=t)}}catch(t){}if(!c)return;let n=null;if(c&&\"object\"==typeof c){const t=Object.keys(c);if(t.length>0){const e=t[0],o=e?c[e]:null;o&&\"object\"==typeof o&&\"layout\"in o&&(n=o.layout)}}const s=document.querySelector(\"[\"+o+'=\"'+t+'\"]');s&&n&&n.forEach((t=>{const e=`--panel-${t.order}-size`;s.style.setProperty(e,t.size.toFixed(l))}))}";
