name: "Vitest"
on: [pull_request]
jobs:
  tests-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --recursive
      - name: Build NPM packages
        run: pnpm run prerelease
      - name: Run tests
        run: cd packages/react-resizable-panels && pnpm run test
